---
collections:
  - name: community.proxmox

  # Community Proxmox collection - manages VMs, containers, and cluster operations
  - name: community.general
    version: ">=8.0.0"

  # Useful for template rendering and advanced operations
  - name: ansible.posix
    version: ">=1.5.0"
